### ISSUE TITLE
"Invalid ICS file" on Android Fairphone

### ISSUE THREAD

**Issue by Jalfro** [danielegobbetti/ICSImport#10]
When I try to use the app I get the notification "Invalid ICS file". The file is not corrupted, as I can still open it with Lightning. Any idea what's going on here? I'm stuck. Thanks in advance.

**Comment by k3b** [comment]
I had similar problems with some ms-exchange and android-4.4.-stock ics files

After upgrading the ics library from ical4j-1.0.5.jar (3 years old) to the current version 1.0.7 the problems were gone on my side.

@danielegobbetti is it possible to update ical4j ?
