### ISSUE TITLE
End time not correct (if other day?)

### ISSUE THREAD

**Issue by TiloGit** [danielegobbetti/ICSImport#6]
hi,

ics with:
DTSTAMP:20141224T171430Z
DTSTART:20141225T010000Z
DTEND:20141225T090000Z

see example here: https://drive.google.com/file/d/0B64LiJqofGGjNkxQcjF2dmVOdE0/view?usp=sharing

after import it only show a one hour event (my local timezone is PST)

here the text of the ICS

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//HowAo//Engage Bookings Calendar//EN
BEGIN:VEVENT
UID:123415@HowAo.com
STATUS:CONFIRMED
DTSTAMP:20141224T171430Z
DTSTART:20141225T010000Z
DTEND:20141225T090000Z
SUMMARY:Modo booking - My Villa - car #1234 - 2000 Red Nissan Sentra  (account 99999)
DESCRIPTION:Car: #1234 - 2000 Red Nissan Sentra \n\nVehicle Notes: \n\nLocation: My Villa\nbehind 5555 Main St in stall 99. In the alley between Main St and 1 St, in the block between Main St and 1 St.
LOCATION:My Villa
SEQUENCE:1
GEO:-123.128566;49.286385
END:VEVENT
END:VCALENDAR

**Comment by danielegobbetti** [comment]
Thanks for the report, I'll try to reproduce it. (Sorry for the long wait! I just wanted to ack that I read the issue today)

**Comment by danielegobbetti** [comment]
It works for me in release 1.3, sorry (again) for the VERY long wait.

**Comment by Gitoffthelawn** [comment]
You just redefined _better late than never_! :-) :-) :-) :+1: 

Although, seriously, it truly is better late than never.  Fixes are always appreciated whenever they occur.  I just happened to get a big smile out of this one! :-)
