### ISSUE TITLE
Add MIME type "application/ics"

### ISSUE THREAD

**Issue by blausand** [danielegobbetti/ICSImport#7]
When i try to open .ics Files attached to eMails in K9-Mail, my Android 5 says "no application found for application/ics!"
Could that be solved by adding this MIME type to your App?

**Comment by David-Guillot** [comment]
:+1:

**Comment by David-Guillot** [comment]
@blausand I don't really know if it's gonna do the trick, but I just made the very simple change to the app manifest, let's hope @danielegobbetti merges it if he considers it okay.

**Comment by blausand** [comment]
Am 9. November 2015 14:56:41 MEZ, schrieb David Guillot <notifications@github.com>:
>@blausand I don't really know if it's gonna do the trick, but I just
>made the very simple change to the app manifest, let's hope
>@danielegobbetti merges it if he considers it okay.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/danielegobbetti/ICSImport/issues/7#issuecomment-155068820

brillant. Open source grows. And grows.
-- 
Diese Nachricht wurde von meinem Taschenrechner gesendet.

**Comment by danielegobbetti** [comment]
Thanks for the PR, I'll merge and tag a release soon after!
